### ISSUE TITLE
Allow for passing in options to the template

### ISSUE THREAD

**Issue by daviesgeek** [monokrome/jaded-brunch#12]
It would be really nice to allow data to be passed from the config into the compiler via the options object for the plugin.

**Comment by daviesgeek** [comment]
Any update on this?

**Comment by daviesgeek** [comment]
Closed due to https://github.com/monokrome/jaded-brunch/pull/13#issuecomment-71337811

**Comment by monokrome** [comment]
@daviesgeek I want to make sure that this issue has been resolved and is working as you would expect. Is everything good now, or is there something else that we should be considering here?

**Comment by daviesgeek** [comment]
Whoops. Thought this needed reopening. But nevermind :)

I was able to pass options to the template like this:

    plugins: {
      jaded: {
        pretty: true,
        locals: {
          environment: 'development',
          magic: true
        }
      }
    }

Thanks! Works great!

**Comment by monokrome** [comment]
Cool. I was worried that I merged something bad when I saw that it was reopened. Glad to see it's working as expected! This should work, too - I think: 

```json
plugins: {
  jaded: {
    jade: {
      pretty: true,
      locals: {
        environment: 'development',
        magic: true
      }
    }
  }
}

```
