### ISSUE TITLE
Warning loadsh deprecated

### ISSUE THREAD

**Issue by samio80** [monokrome/jaded-brunch#19]
npm WARN deprecated lodash@1.2.1: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.

It it possible to update?

**Comment by monokrome** [comment]
@samio80 Someone has mentioned that they want to send an update, but I will make the change if they don't send a pull request in a reasonable amount of time. Thank you for letting me know about this! :)

**Comment by monokrome** [comment]
This has been fixed, so closing the issue. Please feel free to reopen if I've missed anything!
