### ISSUE TITLE
Refactor causing: "Loading of jaded-brunch failed due to jadePath is not defined"

### ISSUE THREAD

**Issue by pseudonamed** [monokrome/jaded-brunch#27]
Hi,

Apologies if I get things wrong.

My package.json looks like:
```
  'brunch': '>= 2.x'
  'jaded-brunch': '>= 2.x'
```
...and it's presenting the following `Loading of jaded-brunch failed due to jadePath is not defined`. 

So I had a look at the repo and it seems there is a refactor happening on `master`. Specifically with [jadePath](https://github.com/monokrome/jaded-brunch/blob/master/src/index.coffee#L88) being out of scope to it's use [here](https://github.com/monokrome/jaded-brunch/blob/master/src/index.coffee#L56).

Changing `jaded-brunch` to explicitly use `2.3.0` or `2.2.4` fixed the issue. 

NPM is mystery to me so I'm not sure why I'm getting `master` which is `2.2.5` in `package.json` when there is no `2.2.5` tag in git. As well as why I don't get `2.3.0` when I have `>= 2.x` in my package.json.

Also I had to clear node_modules locally to recreate the issue which originally happened in during deployment as CI started from a fresh node_modules everytime.

Ciao,
Donavan

**Comment by monokrome** [comment]
@pseudonamed Thanks for the report... I'm fixing it now. So sorry :(

**Comment by monokrome** [comment]
@pseudonamed This should be fixed in 2.2.6. My apologies again for this. Please feel free to reopen if it isn't fixed for you!

**Comment by pseudonamed** [comment]
Thanks for the quick fix, looks good. :)

**Comment by monokrome** [comment]
@pseudonamed Thanks for following up and submitting your report!
